### PR TITLE
Raise ValueError on negative numbers

### LINKED ISSUE #25: croniter('-90 * * * *') raises KeyError
It should raise documented/expected exception like `ValueError` for invalid input.

### PR DESCRIPTION
**Pull request by josegonzalez**
Closes #25

### CODE REVIEW

**Comment by kiorky** [comment]
please change the message on something more appropriate (no negative number, or somthing like that)

**Comment by kiorky** [comment]
this PR has to be rebased

**Comment by josegonzalez** [comment]
Done. The tests themselves remain unchanged since they were updated in a different merged pull request.

**Comment by kiorky** [comment]
"please change the message on something more appropriate (no negative number, or somthing like that)
"

**Comment by josegonzalez** [comment]
Updated.

**Comment by kiorky** [comment]
Thx !

**Comment by int3rlop3r** [comment]
@kiorky @josegonzalez 
Doesn't #65 handle this issue?

**Comment by josegonzalez** [comment]
Maybe they overlap a bit.

**Comment by kiorky** [comment]
They overlap yes, as they handle both input errors.

**Pull request merged**
