### PR TITLE
Creating is_valid class method

### PR DESCRIPTION
**Pull request by otherpirate**

### CODE REVIEW

**Comment by kiorky** [comment]
I validate this PR, but i think i wont have no time (before 1 month)yet to checkin.
Ping me on irc in one month if still not done.

**Comment by otherpirate** [comment]
Hi @kiorky Could you please review this PR?

**Comment by kiorky** [comment]
Hello, im merging and releasing it.
Thx for your patience.

**Comment by otherpirate** [comment]
Hi @kiorky 
Could you please add my name in contributors list at README file?

Best regards.

**Comment by kiorky** [comment]
Sure, Make a PR, it will land in a future release

**Comment by kiorky** [comment]
You are anyway i think in changelog, verifying

**Comment by kiorky** [comment]
here you are: https://pypi.python.org/pypi/croniter/0.3.20#id3
But feel free to push everything that update authors and such :)

**Pull request merged**
