### PR TITLE
feat: support Python 3.6, 3.7

### PR DESCRIPTION
**Pull request by joshuarli**
Hi! Thanks for writing croniter, we use it over at https://github.com/getsentry/sentry.

Just wanted to make sure tests pass on 3.6 + 3.7. Looks like it just works, at least in a local py37 venv. I've updated your CI config and some metadata for 2.7 and 3.4-7.

### CODE REVIEW

**Comment by kiorky** [comment]
Can you not drop python2.6 ?

**Comment by kiorky** [comment]
(Other things looks like LGTM)

**Comment by joshuarli** [comment]
> Can you not drop python2.6 ?

Well, it looks like you commented 2.6 out in travis. Are you suggesting that I uncomment that and if tests still pass on 2.6, undrop 2.6?

**Comment by kiorky** [comment]
travis images does not support well 2.6, but we still support it here, so there is no reason to remove it from trove classifiers even if not tested by travis.

Remove the 2.6 drop and we are good to merge !

**Comment by joshuarli** [comment]
Oh yeah, since support for Python 3.6/7 didn't require any actual code change. Sounds good!

**Pull request merged**
