### PR TITLE
feat: Support for day-or in match

### PR DESCRIPTION
**Pull request by taguchi8s**
Allow the day-or option to be used in the match method.

### CODE REVIEW

**Comment by kiorky** [comment]
Thanks for the feature, but can you something in the readme that explains what does the switch and how to use it ?

Thanks in advance !

**Comment by kiorky** [comment]
btw the official repo is here : https://github.com/kiorky/croniter

Can you reopen the pull request in the good place ?

**Comment by taguchi8s** [comment]
Thanks for the response.
I will re-open it in the official repository.

**Comment by kiorky** [comment]
I dont know if you understood, i want those changes, just that the repo is moving, and it will be easier for the test stack that you open a pull request by forking upon https://github.com/kiorky/croniter !

**Comment by kiorky** [comment]
Damn, i didnt refreshed my browser :).
cool, see you on the other repo !

**Pull request closed without merging**
