### PR TITLE
Implement step cron with a variable base

### LINKED ISSUE #57: KeyError when using '0 4/6 * * *'
This is a valid cron expression. http://crontab.guru/#0_4/6_*_*_*

```
>>> iter = croniter('0 4/6 * * *', base)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/croniter/croniter.py", line 113, in __init__
    t = self.ALPHACONV[i][t.lower()]
KeyError: '4/6'

```

### PR DESCRIPTION
**Pull request by josegonzalez**
Closes #57

### CODE REVIEW

**Comment by kiorky** [comment]
Please rebase the PR

**Comment by kiorky** [comment]
i wa

**Comment by kiorky** [comment]
i want to see tests pass, reopen this pr against my fork (github.com/kiorky/croniter)

**Comment by josegonzalez** [comment]
Rebased against master here, which seems to be triggering tests.

**Comment by kiorky** [comment]
Thx !

**Pull request merged**
