### PR TITLE
Address issue #68

### PR DESCRIPTION
**Pull request by sekikn**
Hi,

I tried to implement a feature referred to in #68 since [other user also wants it](https://issues.apache.org/jira/browse/AIRFLOW-1172).
Is there any chance you could merge this?

### CODE REVIEW

**Comment by kiorky** [comment]
Amazing, sure

**Comment by kiorky** [comment]
Ill review it, when done, your thing will go upstream, here ;)

**Comment by kiorky** [comment]
merged & released, thx !

**Comment by sekikn** [comment]
Thank you very much for reviewing, merging and releasing!

**Pull request merged**
